#!/bin/sh
echo "code formatting by clang-format"
clang-format -i \
             ./unlabeled_mapf/include/*.hpp \
             ./unlabeled_mapf/src/*.cpp \
             ./tests/*.cpp \
             ./app.cpp \
git add ./**/*.cpp
git add ./**/*.hpp
echo "formatting done"
