find_path(GUROBI_INCLUDE_DIRS
  NAMES gurobi_c.h
  HINTS ${GUROBI_DIR} $ENV{GUROBI_HOME}
  PATH_SUFFIXES include)

find_library(GUROBI_LIB_91
  NAMES gurobi gurobi91
  HINTS ${GUROBI_DIR} $ENV{GUROBI_HOME}
  PATH_SUFFIXES lib)

find_library(GUROBI_LIB_C++
  NAMES gurobi gurobi_c++
  HINTS ${GUROBI_DIR} $ENV{GUROBI_HOME}
  PATH_SUFFIXES lib)

set(GUROBI_LIB ${GUROBI_LIB_91} ${GUROBI_LIB_C++})
